# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `chartkick` gem.
# Please instead update this file by running `bin/tapioca gem chartkick`.

# source://chartkick-4.2.0/lib/chartkick/helper.rb:4
module Chartkick
  class << self
    # Returns the value of attribute content_for.
    #
    # source://chartkick-4.2.0/lib/chartkick.rb:18
    def content_for; end

    # Sets the attribute content_for
    #
    # @param value the value to set the attribute content_for to.
    #
    # source://chartkick-4.2.0/lib/chartkick.rb:18
    def content_for=(_arg0); end

    # Returns the value of attribute options.
    #
    # source://chartkick-4.2.0/lib/chartkick.rb:19
    def options; end

    # Sets the attribute options
    #
    # @param value the value to set the attribute options to.
    #
    # source://chartkick-4.2.0/lib/chartkick.rb:19
    def options=(_arg0); end
  end
end

# source://chartkick-4.2.0/lib/chartkick/engine.rb:3
class Chartkick::Engine < ::Rails::Engine; end

# source://chartkick-4.2.0/lib/chartkick/helper.rb:5
module Chartkick::Helper
  # source://chartkick-4.2.0/lib/chartkick/helper.rb:22
  def area_chart(data_source, **options); end

  # source://chartkick-4.2.0/lib/chartkick/helper.rb:18
  def bar_chart(data_source, **options); end

  # source://chartkick-4.2.0/lib/chartkick/helper.rb:14
  def column_chart(data_source, **options); end

  # source://chartkick-4.2.0/lib/chartkick/helper.rb:30
  def geo_chart(data_source, **options); end

  # source://chartkick-4.2.0/lib/chartkick/helper.rb:6
  def line_chart(data_source, **options); end

  # source://chartkick-4.2.0/lib/chartkick/helper.rb:10
  def pie_chart(data_source, **options); end

  # source://chartkick-4.2.0/lib/chartkick/helper.rb:26
  def scatter_chart(data_source, **options); end

  # source://chartkick-4.2.0/lib/chartkick/helper.rb:34
  def timeline(data_source, **options); end

  private

  # don't break out options since need to merge with default options
  #
  # source://chartkick-4.2.0/lib/chartkick/helper.rb:41
  def chartkick_chart(klass, data_source, **options); end

  # https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/hash/deep_merge.rb
  #
  # source://chartkick-4.2.0/lib/chartkick/helper.rb:142
  def chartkick_deep_merge(hash_a, hash_b); end

  # source://chartkick-4.2.0/lib/chartkick/helper.rb:154
  def chartkick_json_escape(s); end
end

# from https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/string/output_safety.rb
#
# source://chartkick-4.2.0/lib/chartkick/helper.rb:152
Chartkick::Helper::JSON_ESCAPE = T.let(T.unsafe(nil), Hash)

# source://chartkick-4.2.0/lib/chartkick/helper.rb:153
Chartkick::Helper::JSON_ESCAPE_REGEXP = T.let(T.unsafe(nil), Regexp)

# source://chartkick-4.2.0/lib/chartkick/version.rb:2
Chartkick::VERSION = T.let(T.unsafe(nil), String)

# for both multiple series and
# making sure hash order is preserved in JavaScript
#
# source://chartkick-4.2.0/lib/chartkick/enumerable.rb:3
module Enumerable
  # source://chartkick-4.2.0/lib/chartkick/enumerable.rb:4
  def chart_json; end
end
