# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `erb_lint` gem.
# Please instead update this file by running `bin/tapioca gem erb_lint`.

# source://erb_lint-0.1.3/lib/erb_lint/version.rb:3
module ERBLint; end

# source://erb_lint-0.1.3/lib/erb_lint/version.rb:4
ERBLint::VERSION = T.let(T.unsafe(nil), String)
