# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mini_portile2` gem.
# Please instead update this file by running `bin/tapioca gem mini_portile2`.

# source://mini_portile2//lib/mini_portile2/version.rb#1
class MiniPortile
  # @return [MiniPortile] a new instance of MiniPortile
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#51
  def initialize(name, version, **kwargs); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#193
  def activate; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#94
  def apply_patch(patch_file); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#143
  def compile; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#128
  def configure; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#124
  def configure_options; end

  # Sets the attribute configure_options
  #
  # @param value the value to set the attribute configure_options to.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#34
  def configure_options=(_arg0); end

  # @return [Boolean]
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#160
  def configured?; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#178
  def cook; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#80
  def download; end

  # @return [Boolean]
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#152
  def downloaded?; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#87
  def extract; end

  # Returns the value of attribute files.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def files; end

  # Sets the attribute files
  #
  # @param value the value to set the attribute files to.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def files=(_arg0); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#232
  def gcc_cmd; end

  # Returns the value of attribute host.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def host; end

  # Sets the attribute host
  #
  # @param value the value to set the attribute host to.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def host=(_arg0); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#147
  def install; end

  # @return [Boolean]
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#171
  def installed?; end

  # Returns the value of attribute logger.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def logger; end

  # Sets the attribute logger
  #
  # @param value the value to set the attribute logger to.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def logger=(_arg0); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#236
  def make_cmd; end

  # Returns the value of attribute name.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#33
  def name; end

  # Returns the value of attribute original_host.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#33
  def original_host; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#117
  def patch; end

  # Returns the value of attribute patch_files.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def patch_files; end

  # Sets the attribute patch_files
  #
  # @param value the value to set the attribute patch_files to.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def patch_files=(_arg0); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#228
  def path; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#73
  def prepare_build_directory; end

  # Returns the value of attribute source_directory.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def source_directory; end

  # Sets the attribute source_directory
  #
  # @param value the value to set the attribute source_directory to.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#69
  def source_directory=(path); end

  # Returns the value of attribute target.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def target; end

  # Sets the attribute target
  #
  # @param value the value to set the attribute target to.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#35
  def target=(_arg0); end

  # Returns the value of attribute version.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#33
  def version; end

  private

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#250
  def archives_path; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#270
  def computed_options; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#258
  def configure_defaults; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#266
  def configure_prefix; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#391
  def detect_host; end

  # Slighly modified from RubyInstaller uri_ext, Rubinius configure
  # and adaptations of Wayne's RailsInstaller
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#487
  def download_file(url, full_path, count = T.unsafe(nil)); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#560
  def download_file_file(uri, full_path); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#565
  def download_file_ftp(uri, full_path); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#506
  def download_file_http(url, full_path, count = T.unsafe(nil)); end

  # command could be an array of args, or one string containing a command passed to the shell. See
  # Process.spawn for more information.
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#418
  def execute(action, command, command_opts = T.unsafe(nil)); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#408
  def extract_file(file, target); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#277
  def files_hashs; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#343
  def log_file(action); end

  # print out a message with the logger
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#474
  def message(text); end

  # @return [Boolean]
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#465
  def newer?(target, checkpoint); end

  # print out a message using the logger but return to a new line
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#480
  def output(text = T.unsafe(nil)); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#246
  def port_path; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#359
  def tar_compression_switch(filename); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#351
  def tar_exe; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#242
  def tmp_path; end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#297
  def verify_file(file); end

  # From: http://stackoverflow.com/a/5471032/7672
  # Thanks, Mislav!
  #
  # Cross-platform way of finding an executable in the $PATH.
  #
  #   which('ruby') #=> /usr/bin/ruby
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#380
  def which(cmd); end

  # @yield [temp_file]
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#598
  def with_tempfile(filename, full_path); end

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#254
  def work_path; end

  class << self
    # GNU MinGW compiled Ruby?
    #
    # @return [Boolean]
    #
    # source://mini_portile2//lib/mini_portile2/mini_portile.rb#42
    def mingw?; end

    # MS Visual-C compiled Ruby?
    #
    # @return [Boolean]
    #
    # source://mini_portile2//lib/mini_portile2/mini_portile.rb#47
    def mswin?; end

    # @return [Boolean]
    #
    # source://mini_portile2//lib/mini_portile2/mini_portile.rb#37
    def windows?; end
  end
end

# source://mini_portile2//lib/mini_portile2/mini_portile.rb#31
MiniPortile::DEFAULT_TIMEOUT = T.let(T.unsafe(nil), Integer)

# source://mini_portile2//lib/mini_portile2/mini_portile.rb#295
MiniPortile::KEYRING_NAME = T.let(T.unsafe(nil), String)

# source://mini_portile2//lib/mini_portile2/mini_portile.rb#350
MiniPortile::TAR_EXECUTABLES = T.let(T.unsafe(nil), Array)

# source://mini_portile2//lib/mini_portile2/version.rb#2
MiniPortile::VERSION = T.let(T.unsafe(nil), String)

# source://mini_portile2//lib/mini_portile2/mini_portile_cmake.rb#3
class MiniPortileCMake < ::MiniPortile
  # @return [MiniPortileCMake] a new instance of MiniPortileCMake
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile_cmake.rb#8
  def initialize(name, version, **kwargs); end

  # source://mini_portile2//lib/mini_portile2/mini_portile_cmake.rb#48
  def cmake_cmd; end

  # source://mini_portile2//lib/mini_portile2/mini_portile_cmake.rb#23
  def configure; end

  # source://mini_portile2//lib/mini_portile2/mini_portile_cmake.rb#13
  def configure_defaults; end

  # source://mini_portile2//lib/mini_portile2/mini_portile_cmake.rb#4
  def configure_prefix; end

  # @return [Boolean]
  #
  # source://mini_portile2//lib/mini_portile2/mini_portile_cmake.rb#32
  def configured?; end

  # source://mini_portile2//lib/mini_portile2/mini_portile_cmake.rb#43
  def make_cmd; end
end

# Monkey patch for Net::HTTP by ruby open-uri fix:
# https://github.com/ruby/ruby/commit/58835a9
#
# source://mini_portile2//lib/mini_portile2/mini_portile.rb#14
class Net::HTTP < ::Net::Protocol
  private

  # source://mini_portile2//lib/mini_portile2/mini_portile.rb#17
  def edit_path(path); end
end
