# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opensearch-ruby` gem.
# Please instead update this file by running `bin/tapioca gem opensearch-ruby`.

module OpenSearch; end

class OpenSearch::Client
  include ::OpenSearch::API
  include ::OpenSearch::API::Shutdown
  include ::OpenSearch::API::Features
  include ::OpenSearch::API::DanglingIndices
  include ::OpenSearch::API::Remote
  include ::OpenSearch::API::Cat
  include ::OpenSearch::API::Tasks
  include ::OpenSearch::API::Snapshot
  include ::OpenSearch::API::Ingest
  include ::OpenSearch::API::Indices
  include ::OpenSearch::API::Nodes
  include ::OpenSearch::API::Cluster
  include ::OpenSearch::API::Actions
  include ::OpenSearch::API::Common

  # See OpenSearch::Transport::Client for initializer parameters
  #
  # @return [Client] a new instance of Client
  def initialize(arguments = T.unsafe(nil), &block); end

  def method_missing(name, *args, &block); end

  # Returns the value of attribute transport.
  def transport; end

  # Sets the attribute transport
  #
  # @param value the value to set the attribute transport to.
  def transport=(_arg0); end

  private

  def open_search_validation_request; end
  def verify_open_search; end

  # @raise [OpenSearch::UnsupportedProductError]
  def verify_version_and_distribution(version, distribution); end
end

OpenSearch::NOT_SUPPORTED_WARNING = T.let(T.unsafe(nil), String)
OpenSearch::SECURITY_PRIVILEGES_VALIDATION_WARNING = T.let(T.unsafe(nil), String)

class OpenSearch::UnsupportedProductError < ::StandardError
  # @return [UnsupportedProductError] a new instance of UnsupportedProductError
  def initialize(message = T.unsafe(nil)); end
end

OpenSearch::VERSION = T.let(T.unsafe(nil), String)
