# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails-erd` gem.
# Please instead update this file by running `bin/tapioca gem rails-erd`.

# Welcome to the API documentation of Rails ERD. If you wish to extend or
# customise the output that is generated by Rails ERD, you have come to the
# right place.
#
# == Creating custom output
#
# If you want to create your own kind of diagrams, or some other output, a
# good starting point is the RailsERD::Diagram class. It can serve as the base
# of your output generation code.
#
# == Options
#
# Rails ERD provides several options that allow you to customise the
# generation of the diagram and the domain model itself. For an overview of
# all options available in Rails ERD, see README.rdoc.
#
# You can specify the option on the command line if you use Rails ERD with
# Rake:
#
#   % rake erd orientation=vertical title='My model diagram'
#
# When using Rails ERD from within Ruby, you can set the options on the
# RailsERD namespace module:
#
#   RailsERD.options.orientation = :vertical
#   RailsERD.options.title = "My model diagram"
#
# source://rails-erd-1.7.1/lib/rails_erd/railtie.rb:1
module RailsERD
  class << self
    # source://rails-erd-1.7.1/lib/rails_erd.rb:37
    def default_options; end

    # source://rails-erd-1.7.1/lib/rails_erd.rb:64
    def load_tasks; end

    # source://rails-erd-1.7.1/lib/rails_erd.rb:62
    def loaded_tasks; end

    # source://rails-erd-1.7.1/lib/rails_erd.rb:61
    def loaded_tasks=(val); end

    # Access to default options. Any instance of RailsERD::Domain and
    # RailsERD::Diagram will use these options unless overridden.
    #
    # source://rails-erd-1.7.1/lib/rails_erd.rb:35
    def options; end

    # Access to default options. Any instance of RailsERD::Domain and
    # RailsERD::Diagram will use these options unless overridden.
    #
    # source://rails-erd-1.7.1/lib/rails_erd.rb:35
    def options=(_arg0); end
  end
end

# source://rails-erd-1.7.1/lib/rails_erd/config.rb:4
class RailsERD::Config
  # @return [Config] a new instance of Config
  #
  # source://rails-erd-1.7.1/lib/rails_erd/config.rb:14
  def initialize; end

  # source://rails-erd-1.7.1/lib/rails_erd/config.rb:18
  def load(extra_config_file = T.unsafe(nil)); end

  # Returns the value of attribute options.
  #
  # source://rails-erd-1.7.1/lib/rails_erd/config.rb:8
  def options; end

  private

  # source://rails-erd-1.7.1/lib/rails_erd/config.rb:43
  def load_file(path); end

  # source://rails-erd-1.7.1/lib/rails_erd/config.rb:52
  def normalize_value(key, value); end

  class << self
    # source://rails-erd-1.7.1/lib/rails_erd/config.rb:29
    def font_names_based_on_os; end

    # source://rails-erd-1.7.1/lib/rails_erd/config.rb:10
    def load(extra_config_file = T.unsafe(nil)); end

    # @return [Boolean]
    #
    # source://rails-erd-1.7.1/lib/rails_erd/config.rb:95
    def use_os_x_fonts?; end
  end
end

# source://rails-erd-1.7.1/lib/rails_erd/config.rb:6
RailsERD::Config::CURRENT_CONFIG_FILE = T.let(T.unsafe(nil), String)

# source://rails-erd-1.7.1/lib/rails_erd/config.rb:5
RailsERD::Config::USER_WIDE_CONFIG_FILE = T.let(T.unsafe(nil), String)

# @private :nodoc:
#
# source://rails-erd-1.7.1/lib/rails_erd.rb:72
module RailsERD::Inspectable
  # source://rails-erd-1.7.1/lib/rails_erd.rb:73
  def inspection_attributes(*attributes); end
end

# Rails ERD integrates with Rails 3. If you add it to your +Gemfile+, you
# will gain a Rake task called +erd+, which you can use to generate diagrams
# of your domain model.
#
# source://rails-erd-1.7.1/lib/rails_erd/railtie.rb:5
class RailsERD::Railtie < ::Rails::Railtie; end
