require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  NewCops: enable
  # TODO: Uncomment when https://github.com/Shopify/erb-lint/pull/194 lands.
  # erb_lint confines us to an old version of Rubocop, which doesn't have SuggestExtensions.
  # SuggestExtensions: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/GuardClause:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AccessorGrouping:
  EnforcedStyle: separated
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/LambdaCall:
  Exclude:
    - '**/*.jbuilder'

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments

RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false
