require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance
  - rubocop-minitest
  - rubocop-sorbet

AllCops:
  NewCops: enable
  SuggestExtensions: true

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/GuardClause:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AccessorGrouping:
  EnforcedStyle: separated
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/LambdaCall:
  Exclude:
    - '**/*.jbuilder'

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
Rails/ActionControllerFlashBeforeRender:
  Enabled: false
