require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance
  - rubocop-minitest
  - rubocop-sorbet
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  SuggestExtensions: true

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/NegatedIf:
  EnforcedStyle: postfix
Style/ClassAndModuleChildren:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AccessorGrouping:
  EnforcedStyle: separated
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/LambdaCall:
  Exclude:
    - '**/*.jbuilder'
Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowedMethods:
    - require
    - require_relative
    - require_dependency
    - yield
    - raise
    - puts
    - execute
  Exclude:
    - '/**/Gemfile'
Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/VariableNumber:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
Rails/ActionControllerFlashBeforeRender:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Minitest/MultipleAssertions:
  Enabled: false

FactoryBot/ExcessiveCreateList:
  Enabled: false
