# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AddNewUserToMailingListJob`.
# Please instead update this file by running `bin/tapioca dsl AddNewUserToMailingListJob`.

class AddNewUserToMailingListJob
  class << self
    sig { params(user: ::User).returns(T.any(AddNewUserToMailingListJob, FalseClass)) }
    def perform_later(user); end

    sig { params(user: ::User).void }
    def perform_now(user); end
  end
end
