# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SubjectAreaHelper`.
# Please instead update this file by running `bin/tapioca dsl SubjectAreaHelper`.

module SubjectAreaHelper
  include Kernel
  include ActionView::Helpers
  include Devise::Controllers::Helpers
end
