service: ucla-registrar-scraper
useDotenv: true

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  timeout: 120
  region: 'us-west-1'
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: '*'
  tracing:
    lambda: true
  environment:
    LOGGING: ${env:LOGGING, ''}
    LOG_LEVEL: ${env:LOG_LEVEL, 'warn'}
    DATABASE_URL: ${env:DATABASE_URL, ''}
    BATCH_SIZE: ${env:BATCH_SIZE, 200}
    MAX_GOROUTINES: ${env:MAX_GOROUTINES, 20}
    DD_FLUSH_TO_LOG: ${env:DD_FLUSH_TO_LOG, false}
    DD_TRACE_ENABLED: ${env:DD_TRACE_ENABLED, false}
    DD_MERGE_XRAY_TRACES: ${env:DD_MERGE_XRAY_TRACES, false}
    DRY_RUN: ${env:DRY_RUN, true}
    USE_PREPARED_STATEMENTS: ${env:USE_PREPARED_STATEMENTS, false}
    LAMBDA_INVOKE_DELAY_MS: ${env:LAMBDA_INVOKE_DELAY_MS, 50}
    NOTIFICATION_ENDPOINT: ${env:NOTIFICATION_ENDPOINT, ''}
    NOTIFICATION_ENDPOINT_TOKEN: ${env:NOTIFICATION_ENDPOINT_TOKEN, ''}

package:
  individually: true
  patterns:
    - '!./**'
    - './bin/**'

custom:
  # Payloads
  currentTerm:
    term:
      term: '24F'
      id: 78
    shouldInsertEnrollmentData: true
  # summerTerm:
  #   term:
  #     term: '231'
  #     id: 112
  #   shouldInsertEnrollmentData: true

functions:
  FetchSubjectAreas:
    name: fetch-subject-areas
    handler: bootstrap
    package:
      artifact: bin/fetch-subject-areas.zip
    events:
      # Top of every month at 11:15pm UTC
      - schedule:
          rate: cron(15 23 1 * ? *)
          input: ${self:custom.currentTerm}
      # - schedule:
      #     rate: cron(15 23 1 * ? *)
      #     input: ${self:custom.summerTerm}

  FetchCourses:
    name: fetch-courses
    handler: bootstrap
    package:
      artifact: bin/fetch-courses.zip
    events:
      # Every day at 11:45pm UTC
      - schedule:
          rate: cron(45 23 * * ? *)
          input: ${self:custom.currentTerm}
      # Every day at 11:50pm UTC
      # - schedule:
      #     rate: cron(50 23 * * ? *)
      #     input: ${self:custom.summerTerm}

  FetchSections:
    name: fetch-sections
    handler: bootstrap
    package:
      artifact: bin/fetch-sections.zip
    timeout: 420 # 7 minutes
    events:
      # Every hour at XX:25
      - schedule:
          rate: cron(25 * * * ? *)
          input: ${self:custom.currentTerm}
      # Every hour at XX:35
      # - schedule:
      #     rate: cron(35 * * * ? *)
      #     input: ${self:custom.summerTerm}

  FetchCourseDescriptions:
    name: fetch-course-descriptions
    handler: bootstrap
    package:
      artifact: bin/fetch-course-descriptions.zip
    events:
      # Top of every month at 11:40pm UTC
      - schedule:
          rate: cron(40 23 1 * ? *)
          input: {}

resources:
  Resources:
    FetchSubjectAreasLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: 7
    FetchCoursesLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: 7
    FetchSectionsLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: 7
    FetchCourseDescriptionsLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: 7
