name: Deploy
on:
  push:
    branches:
      - main

concurrency:
  group: 'main-deploy'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            lambdas:
              - 'lambdas/**'
            rails:
              - '!lambdas/**'

      - name: Deploy Lambdas
        if: steps.filter.outputs.lambdas == 'true'
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./lambdas && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Rails app to dokku
        if: steps.filter.outputs.rails == 'true'
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.SSH_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: main
