name: Go
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/golang.yml
      - lambdas/**

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: lambdas

  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambdas
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: go test ./... -coverprofile=coverage.txt
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: lambdas
          flags: go
          fail_ci_if_error: true
